version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
    - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
        
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      
  postgre:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 258495
      POSTGRES_USER: postgres
      POSTGRES_DB: musicProgram
      
  springboot-mongodb:
    image: music
    build: ./
    depends_on:
      - mongodb
      - redis
      - postgre
    ports:
      - 8082:8082
    links:
      - mongodb
      - redis
      - postgre
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb:27017
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: example
      SPRING_DATA_MONGODB_DATABASE: musicProgram
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgre:5432/musicProgram
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 258495
volumes:
  mongo:
  
  pgdata: